### PR TITLE
NEON form update

### PR DESCRIPTION
**Pull request by kaylima**
This replaces the existing NEON form code with updated code for use with reCAPTCHA V2. The form is currently throwing an error which this resolves.

### CODE REVIEW

**Comment by kaylima** [comment]
This is related to Help Scout conversation #1816.

**Comment by benlk** [comment]
Before: 

screen shot 2018-03-19 at 10 25 06 am


After:

screen shot 2018-03-19 at 10 24 10 am

So this needs some styling work, and the duplicate heading to be removed.

**Comment by kaylima** [comment]
@benlk Duplicate "sign up" header removed and labels slightly updated. More styling can be done after client reviews on staging.

**Review by tylermachado — APPROVED** [review]
👍

**Pull request merged**
